name: Site deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm build

  lint-json:
    needs: build
    runs-on: ubuntu-latest
    steps:
        with:
          node-version: 20
      - run: jsonlint src/challengelist.json
      - run: jsonlint src/tiers.json

  publish:
    needs: lint-json
    runs-on: ubuntu-latest
    steps:
        with:
          node-version: 20
      - run: npm run deploy
